version: "3"
services:
  server:
    build:
      context: ./Server
      dockerfile: ./log-nine-backend/Dockerfile
    ports:
      - "8082:8080"
    volumes:
      - ./data:/app/data
    networks:
      - log-nine-network

  frontend:
    build:
      context: ./Webpage
      args:
        - VITE_APP_BACKEND_URL=http://localhost:8082
    ports:
      - "8081:4173"
    depends_on:
      - server
    networks:
      - log-nine-network

networks:
  log-nine-network:
    driver: bridge
